language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: dev
before_script:
  - "npm i -g gatsby"
  - "npm i --unsafe-perm=true"
script:
  - "npm run test"
after_success:
  - "npm run deploy"
